### PR TITLE
Make sure to restart after change on app crash

### LINKED ISSUE #96: Watch does not restart the process once it crashes
Message says the process is crashed and waiting for changes to restart however nothing happens after changes. Seeing the comments here, is this a WIP feature? I am using node v8.11.3 on windows 10.

```
process.on("uncaughtException", err => {
  console.log(err);
  const message = chalk.red(
    "[fastify-cli] app crashed - waiting for file changes before starting..."
  );
  // fastify.close(exit) // It's looks that only happend fastify normally startup. so we should detect fastify is normally runing, it's normally running that graceful exit happen, other case I think it's better immediately exec process.exit(1)
  //setTimeout(exit.bind({ message }), TIMEOUT).unref();
  exit.bind({ message })();
});
```

### PR DESCRIPTION
**Pull request by cemremengu**
Fixes #96

### CODE REVIEW

**Comment by mcollina** [comment]
How can I test this?

**Comment by cemremengu** [comment]
I think I have an idea

**Comment by cemremengu** [comment]
Nevermind, I talked too early. I think chokidar watch can't catch change events in travis CI anyways 😞

File: lib/watch/index.js [hunk 1]
```diff
@@ -75,6 +75,7 @@ const watch = function (args) {
           console.log(err)
           stop(watcher, err)
         }
+        childs.push(run('restart'))
```
Comment (mcollina) [inline lib/watch/index.js]: I think this whole try-catch needs a fix. The condition `if (!childs.length === 0)`  can never be `true`, because `!childs.length`  will either be `true`  or `false`, but never `0`.

Comment (cemremengu) [reply lib/watch/index.js]: I think it actually meant length !== 0 which I changed in #107
