### PR TITLE
fix: should ensure can access all decorators from app built with `helper.build`

### LINKED ISSUE #622: Can't access plugin inside tests
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I've generated the project using the cli and then I modified my app.ts file so that it looks like this:
```
import { join } from 'path';
import AutoLoad, {AutoloadPluginOptions} from '@fastify/autoload';
import { FastifyInstance, FastifyPluginAsync } from 'fastify';
import { fastifyPostgres } from '@fastify/postgres';
import fastifySwagger from '@fastify/swagger';
import fastifySwaggerUi from '@fastify/swagger-ui';
import sensible from '@fastify/sensible';
import cors from '@fastify/cors'

export type AppOptions = {} & Partial<AutoloadPluginOptions>;


// Pass --options via CLI arguments in command to enable these options.
const options: AppOptions = {}

const app: FastifyPluginAsync<AppOptions> = async (fastify: FastifyInstance, opts: any): Promise<void> => {
  fastify.register(sensible)

  fastify.register(fastifyPostgres, {
    connectionString: `postgres://${process.env.DB_USER}:${process.env.DB_PASSWORD}@${process.env.DB_HOST}/${process.env.DB_DATABASE}`
  })

  fastify.register(fastifySwagger, { hideUntagged: true })
  fastify.register(fastifySwaggerUi, {
    routePrefix: '/docs',
    uiConfig: { docExpansion: 'list' }
  })

  await fastify.register(cors, {})

  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'routes'),
    options: opts
  })

}

export default app;
export { app, options }
```

The problem is that when i try to use the pg plugin inside a test I get an error `Cannot read properties of undefined (reading 'query')`, which makes me believe that the plugin hasn't been registered, but I don't know how to do it.

### PR DESCRIPTION
**Pull request by jean-michelet**
Fixes #622

### CODE REVIEW

File: helper.d.ts [hunk 1]
```diff
@@ -1,8 +1,12 @@
 import fastify from 'fastify'
 
+type BuildOptions = {
+    skipOverride?: boolean
+}
```
Comment (jean-michelet) [inline helper.d.ts:5]: I can think of other scenarios where this might be useful, such as the `beforeReady` callback which could allow decorators to be overridden, e.g. to make a method fail.

**Comment by jordanebelanger** [comment]
I really need this fix merged in 😊

**Comment by jean-michelet** [comment]
> I really need this fix merged in 😊

Next time, feel free to push a PR with unit tests. We'd be happy to review your code and merge the fixes.

**Comment by jean-michelet** [comment]
Ready for review @mcollina @Eomm

**Comment by jean-michelet** [comment]
@jordanebelanger 

Even if I've already pushed a PR, if the tests are broken and you have the right solution, that's OK to push a new PR or to tell me why my PR is wrong and how I can fix it.

Fastify is community driven, so maintainers don't usually solve bugs for you.

I left you this message to save you time, not to lecture you, just to be clear ^

**Review by mcollina — APPROVED** [review]
lgtm
