### PR TITLE
Fix watch regression

### LINKED ISSUE #513: Generate typescript app not starting
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Plugin version

3.0.0

### Node.js version

14.17.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04.4

### Description

When trying to start a just generate app using typescript the browser shows 
image

When trying to generate and start a js fastify app everything work fine  but with typescript doesn't start.

This is what  it shows the console.
image

### Steps to Reproduce

Generate an app, and trying to start it.
```
fastify generate <app-name> --lang=ts

npm install

npm start dev
```

### Expected Behavior

Start the app normally

### LINKED ISSUE #518: Watch never restarts the server after multiple watch events (v4.2.0)
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.0

### CLI version

4.2.0

### Node.js version

18.4.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

After updating to fastify-cli 4.2.0 from 4.1.1, it seems as though modifying watched files can cause the fastify-cli server to stop the server and never restart. Killing the process after this happens, the following error is observed sometimes:

```console
% Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
[fastify-cli] app crashed - waiting for file changes before starting...
[1656790027711] INFO (42069 on MacBook-Pro.bec.local): Server listening at http://0.0.0.0:3000
```

A samble of verbose logging prior to the server not responding/restarting looks like this:

```
[fastify-cli] watch - 'addDir' occurred on 'public/hooks'
[fastify-cli] watch - 'addDir' occurred on 'public/lib'
[fastify-cli] watch - 'addDir' occurred on 'public/login'
[fastify-cli] watch - 'addDir' occurred on 'public/logout'
[fastify-cli] watch - 'addDir' occurred on 'public/register'
[fastify-cli] watch - 'addDir' occurred on 'public/resources'
[fastify-cli] watch - 'addDir' occurred on 'public/tags'
```

After these messages print, the server is no longe accepting requests. 

### Steps to Reproduce

Start a fastify-cli server in watch mode running fastify-cli 4.2.0 and then trigger some file changes. A `mkdir -p` works well. The server restarts if there are only one or two file watch actions at a time. It will not restart if there are 3-4 actions at a time. Downgrading the CLI to 4.1.1 restore a functional watch mode. 

[Sample repo](https://github.com/ballpit/fastify-cli-bug)

### Expected Behavior

Server should eventually accept requests after files change in watch mode.

### PR DESCRIPTION
**Pull request by bcomnes**
This fixes tests that were not passing on master, improved tests to better match behavior and also fix the regression introduced in https://github.com/fastify/fastify-cli/pull/511 described in https://github.com/fastify/fastify-cli/issues/518 and https://github.com/fastify/fastify-cli/issues/513 and https://github.com/fastify/fastify-cli/pull/515.

I will push up a regression test asap, but I want to validate these changes pass in CI here at this point. 

Fixes #513.
Fixes #518.

#### Checklist

- [x] run `npm run test` ~~and `npm run benchmark`~~
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

File: lib/watch/index.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ const watch = function (args, ignoreWatch, verboseWatch) {
     })
 
     _child.on('exit', function (code, signal) {
-      if (!code) {
+      if (code > 0) {
```
Comment (Eomm) [inline lib/watch/index.js:51]: Could you describe the intent here?

`!0` would be `true`, while `0 > 0` is `false` so I don't get why this inversion

**Comment by mcollina** [comment]
CI is failing

File: lib/watch/index.js (hunk 1 above)
Comment (mcollina) [reply lib/watch/index.js:51]: We can delete this code block

Comment (bcomnes) [reply lib/watch/index.js:51]: It seems like the idea was that if code can either be null or an exit code integer. In the case of a > 0 code, the watcher should stop. In the case of null or 0, restart. It was ignoring > 0 codes before, mostly resulting in desired behavior. 

I can also just remove the block.

**Comment by bcomnes** [comment]
Darn looking into it.

File: lib/watch/index.js (hunk 1 above)
Comment (BigGillyStyle) [reply lib/watch/index.js:51]: While working through Fastify CLI generated JS and TS projects, I _did_ find after changing an app file that the `code` would be `1` in each case I tried...leading to the `stop()` call in line 52 here.  However, removing the `if` block altogether seemed to produce identical behavior.  I don't understand enough of what is going on to determine which option is correct.  I don't know if either choice might lead to dangling processes or not.

Comment (BigGillyStyle) [reply lib/watch/index.js:51]: I guess I should also note that outside the scenario of the app restarting due to a source file change, I otherwise observed that the `code` would be `0` or `null`.

Comment (bcomnes) [reply lib/watch/index.js:51]: Ah ok. Sounds like we should stick with the original behavior and just remove the switch block all together then.  Sorry to add more noise, I didn't pick up on that caveat. 

If I find some time today I'll see if I can investigate the tests failing. 

I noticed that the (currently disabled) watch tests were disabled in ci due to lack of chokidar support for Linux (or windows)? I wonder, if we can restore these tests, could we run them in the macOS image?

Comment (bcomnes) [reply lib/watch/index.js]: Cherry picked your patch that does this.

**Comment by bcomnes** [comment]
Oooookie dokie. This should be good to go, CI passing in my fork:

https://github.com/bcomnes/fastify-cli/actions/runs/2606233931

I also confirmed turning on these tests would have caught the regression in #511.

I also cherry picked @BigGillyStyle's patch so he's on the commit list.

File: test/start.test.js [hunk 2]
```diff
@@ -591,9 +592,6 @@ test('should start the server with watch and verbose-watch options that the chil
     await fastifyEmitter.stop()
   })
 
-  await once(fastifyEmitter, 'start')
-  t.pass('should receive start event')
-
```
Comment (bcomnes) [inline test/start.test.js:596]: I'm not sure why, but these start events never fire anymore.

**Comment by BigGillyStyle** [comment]
> I also cherry picked @BigGillyStyle's patch so he's on the commit list.

Heh heh...thanks for doing that, but no worries either.  Mainly hoping I can help with the solution and not add noise 😄  I'll go ahead and close my PR.  Thanks @bcomnes and @mcollina

**Comment by bcomnes** [comment]
Darn another windows timeout. Let me increase the timeout on that file.

**Comment by bcomnes** [comment]
Sorry, maybe try one more time. I increase the timeout on tests. Seems as though the windows tests fail randomly.
