### PR TITLE
fix: fixed test script in typescript template project

### LINKED ISSUE #320: Typescript template tests are not working
## 🐛 Bug Report

As seen in output below, running npm test doesnt work. It looks similar to #303, but as it's error while importing tap there is not reason to be anything with autoload. 

**Setting "esModuleInterop" to true in tsconfig.json fix it.** 
I found that it's already fixed in #304, but still not merged.

## To Reproduce

```js
❯ fastify generate fastify-sandbox --lang=ts
generated .gitignore
generated tsconfig.json
generated test/helper.ts
generated src/app.ts
generated test/tsconfig.test.json
generated test/plugins/support.test.ts
generated test/routes/example.test.ts
generated src/plugins/README.md
generated src/routes/README.md
generated test/routes/root.test.ts
generated src/plugins/sensible.ts
generated src/plugins/support.ts
generated src/routes/root.ts
generated src/routes/example/index.ts
--> reading package.json in fastify-sandbox
edited package.json, saving
saved package.json
--> project fastify-sandbox generated successfully
run 'npm install' to install the dependencies
run 'npm start' to start the application
run 'npm build:ts' to compile the typescript application
run 'npm run dev' to start the application with pino-colada pretty logging (not suitable for production)
run 'npm test' to execute the unit tests
❯ cd fastify-sandbox
❯ pnpm i
Packages: +422
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/nezouse/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 423, reused 422, downloaded 1, added 422, done
 WARN  Failed to find "/fsevents/2.3.2" in lockfile during hoisting. Next aliases will not be hoisted: fsevents

dependencies:
+ fastify 3.12.0
+ fastify-autoload 3.5.2
+ fastify-cli 2.8.0
+ fastify-plugin 3.0.0
+ fastify-sensible 3.1.0

devDependencies:
+ @types/node 14.14.31
+ @types/tap 14.10.2
+ concurrently 6.0.0
+ fastify-tsconfig 1.0.1
+ tap 14.11.0
+ typescript 4.2.2
❯ pnpm test

> fastify-sandbox@1.0.0 test /home/nezouse/fastify-sandbox
> npm run build:ts && tsc -p test/tsconfig.test.json && tap test/**/*.test.ts


> fastify-sandbox@1.0.0 build:ts /home/nezouse/fastify-sandbox
> tsc

test/helper.ts:5:8 - error TS1259: Module '"/home/nezouse/fastify-sandbox/node_modules/.pnpm/@types/tap@14.10.2/node_modules/@types/tap/index"' can only be default-imported using the 'esModuleInterop' flag

5 import tap from 'tap';
         ~~~

  node_modules/.pnpm/@types/tap@14.10.2/node_modules/@types/tap/index.d.ts:13:1
    13 export = tap;
       ~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.


Found 1 error.

 ERROR  Test failed. See above for more details.
```

## Expected behavior

```js
❯ npm test

> fastify-sandbox@1.0.0 test /home/nezouse/fastify-sandbox
> npm run build:ts && tsc -p test/tsconfig.test.json && tap test/**/*.test.ts


> fastify-sandbox@1.0.0 build:ts /home/nezouse/fastify-sandbox
> tsc

 PASS  test/plugins/support.test.ts 1 OK 48.572ms
 PASS  test/routes/example.test.ts 1 OK 2s
 PASS  test/routes/root.test.ts 1 OK 2s

                         
  🌈 SUMMARY RESULTS 🌈  
                         

Suites:   3 passed, 3 of 3 completed
Asserts:  3 passed, of 3
Time:     8s
--------------------|----------|----------|----------|----------|-------------------|
File                |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------|----------|----------|----------|----------|-------------------|
All files           |      100 |      100 |      100 |      100 |                   |
 src                |      100 |      100 |      100 |      100 |                   |
  app.ts            |      100 |      100 |      100 |      100 |                   |
 src/plugins        |      100 |      100 |      100 |      100 |                   |
  sensible.ts       |      100 |      100 |      100 |      100 |                   |
  support.ts        |      100 |      100 |      100 |      100 |                   |
 src/routes         |      100 |      100 |      100 |      100 |                   |
  root.ts           |      100 |      100 |      100 |      100 |                   |
 src/routes/example |      100 |      100 |      100 |      100 |                   |
  index.ts          |      100 |      100 |      100 |      100 |                   |
--------------------|----------|----------|----------|----------|-------------------|
```

## Your Environment

- *node version*: v14.15.5
- *fastify version*: template installed as today, 
```js
{
    "fastify": "^3.0.0",
    "fastify-cli": "^2.8.0"
}
```
- *os*: Linux on WSL

### PR DESCRIPTION
**Pull request by alemagio**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Fixes #320 

@fox1t 
I did not add `esModuleInterop: true` to `tsconfig.test.json` because changing the import of tap makes it not necessary.
Do you think it is a good practice to add it anyway?

### CODE REVIEW

File: templates/app-ts/__taprc [hunk 1]
```diff
@@ -0,0 +1,3 @@
+test-env: [
+  TS_NODE_PROJECT=./test/tsconfig.test.json
```
Comment (mcollina) [inline templates/app-ts/__taprc:2]: why is this needed? why is this a single test file?

**Comment by fox1t** [comment]
If we want to enforce `esModuleInterop: true,` we should do it at the https://github.com/fastify/tsconfig level to enforce everywhere the same setting (since it also impacts our users).
Let's merge this without touching the tsconfig.json and open a new PR on https://github.com/fastify/tsconfig, bump the major, and update everywhere it needs to be updated.

File: generate.js [hunk 2]
```diff
@@ -45,7 +45,7 @@ const typescriptTemplate = {
   dir: 'app-ts',
   main: 'app.ts',
   scripts: {
-    test: 'npm run build:ts && tsc -p test/tsconfig.test.json && tap test/**/*.test.ts',
+    test: 'tap test/**/*.test.ts',
```
Comment (fox1t) [inline generate.js:48]: Here we want to be sure that the project builds.
```suggestion
    test: 'npm run build:ts && tap test/**/*.test.ts',
```

File: templates/app-ts/__taprc (hunk 1 above)
Comment (fox1t) [inline templates/app-ts/__taprc:2]: I like using this! Didn't know that it was possible to add env vars to `.taprc`! Well done.

**Review by fox1t — DISMISSED** [review]

File: templates/app-ts/__taprc (hunk 1 above)
Comment (alemagio) [reply templates/app-ts/__taprc:2]: Recent discovery for me too. :partying_face:

**Comment by mcollina** [comment]
I don't think we want to force a `esModuleInterop: true` to all our users. It definitely should be set in the template because we need it for tap.

**Comment by alemagio** [comment]
> I don't think we want to force a `esModuleInterop: true` to all our users. It definitely should be set in the template because we need it for tap.

Importing tap like `import * as tap from 'tap'` makes it not required, the error is solved and tests run.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
@fox1t wdyt? Can this land?

File: generate.js [hunk 3]
```diff
@@ -45,7 +45,7 @@ const typescriptTemplate = {
   dir: 'app-ts',
   main: 'app.ts',
   scripts: {
-    test: 'npm run build:ts && tsc -p test/tsconfig.test.json && tap test/**/*.test.ts',
+    test: 'npm run build:ts && tap test/**/*.test.ts',
```
Comment (climba03003) [inline generate.js:48]:
```suggestion
    test: 'npm run build:ts && tap "test/**/*.test.ts"',
```
It is prefer to use quote here, because it can prevent the different of `globstar` behavior from `shell` and `platform`.
More discussion in [here](https://github.com/fastify/fastify-swagger/pull/351#discussion_r568819289)

**Review by climba03003 — CHANGES_REQUESTED** [review]

**Review by climba03003 — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by rubiagatra** [comment]
any update on this PR ?

**Review by mcollina — APPROVED** [review]
lgtm
